DROP DATABASE IF EXISTS mypsl;
CREATE DATABASE mypls;
USE mypls;

DROP TABLE IF EXISTS user;
CREATE TABLE user (
  email VARCHAR(100) NOT NULL
  fName VARCHAR(75) NOT NULL DEFAULT '',
  lName VARCHAR(100) NOT NULL DEFAULT '',
  password VARCHAR(20) NOT NULL DEFAULT,
  PRIMARY KEY (email),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

